# Minimal makefile for Sphinx documentation
#

# You can set these variables from the command line, and also
# from the environment for the first two.
SPHINXOPTS    ?=
SOURCEDIR     = source
BUILDDIR      = build

doc:
	@mkdocs build

.PHONY: html Makefile clean

clean:
	@rm -rf site