site_name: Manim for ISA

nav:
  - index.md
  - Introductions:
    - 0-introductions/01-scenes.md
    - 0-introductions/02-animation-apis.md
    - 0-introductions/03-animation-flow.md
    - 0-introductions/04-placement.md
  - References:
    - 1-references/index.md
    - Objects:
      - 1-references/10-objects/index.md
      - 1-references/10-objects/11-register-unit.md
      - 1-references/10-objects/12-function-unit.md
      - 1-references/10-objects/13-memory-unit.md
      - 1-references/10-objects/14-element-unit.md
    - Animations:
      - 1-references/20-animation/index.md
      - 1-references/20-animation/21-register-animation.md
      - 1-references/20-animation/22-function-animation.md
      - 1-references/20-animation/23-memory-animation.md
    - Scene:
      - 1-references/30-scene/index.md
      - 1-references/30-scene/31-color-map.md
      - 1-references/30-scene/32-placement.md
      - 1-references/30-scene/33-animation-flow.md
      - 1-references/30-scene/34-refer-count.md
      - 1-references/30-scene/35-data_flow.md

theme:
  name: "material"
  features:
    - navigation.indexes

plugins:
  - search
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          paths: [..]
          options:
            show_source: False

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format